matrix:
  include:
    - script:
        - swiftlint lint --strict
        - set -o pipefail
        - xcodebuild $XCODE_ACTION $WORKSPACE -scheme "FyydKit-macOS" | xcpretty
        - xcodebuild $XCODE_ACTION $WORKSPACE -scheme "FyydKit-iOS" -sdk iphonesimulator -destination "OS=11.0,name=iPhone 7" | xcpretty
        - xcodebuild $XCODE_ACTION $WORKSPACE -scheme "FyydKit-tvOS" -sdk appletvsimulator -destination "OS=11.0,name=Apple TV 1080p" | xcpretty
        - xcodebuild build $WORKSPACE -scheme "FyydKit-watchOS" -sdk watchsimulator | xcpretty
      env:
        - JOB=Xcode
        - WORKSPACE="-workspace FyydKit.xcworkspace"
        - XCODE_ACTION="build-for-testing test-without-building"
      os: osx
      osx_image: xcode9
      language: objective-c
      cache: cocoapods
    - script:
        - swift build
        - swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode9
      language: objective-c
